The Transparent Web
===================

Bridging the Chasm in Web Development
-------------------------------------

*The Transparent Web*  is a book that I'm writing about some
"next-generation" web frameworks that meld the server-side and client-side
code that we're all used to writing.

### The Frameworks

- [Rails](http://rubyonrails.org) (for comparison)
- [Meteor](http://www.meteor.com)
- [Opa](http://opalang.org)
- [Ur/Web](http://www.impredicative.com/ur/)
- [Elm](http://elm-lang.org) (front-end only)

### Presentations

- [2012 Aug 18](/blog.html#2012-08-22) - Given for BarCamp Madison Link to
  [slides](http://www.slideshare.net/twopoint718/the-transparent-web-14023703).
- [2012 Sept 10](http://www.meetup.com/MadisonJS/events/78545822/) - Given
  for MadJS (only about Opa). Link to [slides]().

### The Book

The book is a work-in-progress over on LeanPub: [The Transparent Web](https://leanpub.com/transparentweb)
