The Transparent Web
===================

Bridging the Chasm in Web Development
-------------------------------------

*The Transparent Web*  is a book that I'm writing about some
"next-generation" web frameworks that meld the server-side and client-side
code that we're all used to writing.

### The Frameworks

- [Opa](http://opalang.org)
- [Ur/Web](http://www.impredicative.com/ur/)

### Presentations

- [2012 Aug 18](/blog.html#2012-08-22) - Given for BarCamp Madison Link to
  [slides](http://www.slideshare.net/twopoint718/the-transparent-web-14023703).
- [2012 Sept 10](http://www.meetup.com/MadisonJS/events/78545822/) - Given
  for MadJS (only about Opa). Link to [slides]().

### The Book

Here is a speculative table of contents.  I will either make the following
links *work* as the chapters are written, or they'll be changed to reflect
what's really going in the book.  I would *love* to hear feedback on any of
these entries!

#### Table of Contents

- Introduction
- The "Chasm"
- Client-side/Server-side
- The "Control" - A tutorial webapp in modern MVC style
- Opa
- Ur/Web
