# Colophon

## Software

<a href="http://www.gnu.org/licenses/old-licenses/gpl-2.0.html"><div
style="float: right">![gpl v2](img/cc-gnu-gpl.png)</div></a> This site was
produced using [yst](https://github.com/jgm/yst) (a static site generator
written in [Haskell](http://haskell.org)).  yst is licensed under the [GNU GPL
v2](http://www.gnu.org/licenses/gpl-2.0.html).  

<a href="http://www.gnu.org/licenses/agpl-3.0.html"><div style="float:
right">![agpl v3](img/agplv3-88x31.png)</div></a> The site is licensed under
the [AGPL v3](http://www.gnu.org/licenses/agpl-3.0.html) or any later version.
You are welcome to [obtain the
source](http://github.com/twopoint718/sencjw.com) on
[github.com](http://github.com).  After cloning the source, all you need to do
is to run `yst` in the root of the directory.

## Hardware

The generated site is hosted on a
[SheevaPlug](http://en.wikipedia.org/wiki/SheevaPlug) plug computer.  This is a
low-powered SOC server using between three and seven watts.

## Words

<a href="http://creativecommons.org/licenses/by-sa/3.0/"><div style="float: right">![cc
by-sa](img/cc-by-sa.png)</div></a> My writings (that are not considered code)
are licensed [CC BY-SA](http://creativecommons.org/licenses/by-sa/3.0/) 
