# Contact Info

 * @twopoint718 ([identi.ca][0], [twitter][1])
 * twopoint718 (IRC <http://freenode.net>)
 * MadLUG Steering Committee ([Madison Linux User Group][2], [Meetup.com page][3])
 * mail
   ([christopher.j.wilson@gmail.com](mailto:christopher.j.wilson@gmail.com),
   [chris@sencjw.com](chris@sencjw.com))

[0]: http://identi.ca/twopoint718
[1]: http://twitter.com/twopoint718
[2]: http://madisonlinux.org
[3]: http://meetup.com/madlug

# About Me

My name's Chris Wilson.  I'm a sciency kinda dude that's worked mostly
in academic settings (national lab, university) and I like that a
whole bunch.  I've always been interested in more stuff than I could
possibly really know well; among them: science, technology, codes,
econ, radio, sailing, biking, music, movies, the future, and also the
past (I hope that I'm a *little* bit less likely to be doomed to
repeat it).

And, of course, I love programming and computers.  I was fascinated by
Linux back around 1999, but really didn't get rolling until a bit
later.  I played with slackware enough to compile my Fortran 77 code
for my computational physics class the next year.  I handn't yet taken
the full-Linux plunge and so I had a terminal-only computer stuffed
under my dorm bed for when I needed `f77` or `g++`.  From there I
started writing reports using `LaTeX` in `nedit` on the school's SGI
O2s and was pretty much hooked on *NIX.  I was shown around Red Hat
and Fedora Linux by a seasoned perl hacker who also inducted me into
the church of Emacs around 2002 at the rank of acolyte.  This was a
time of much perl hackery (I loved the book [Computers and the
Imagination](http://www.amazon.com/Computers-imagination-Visual-adventures-beyond/dp/0312061315/ref=sr_1_1?s=books&ie=UTF8&qid=1313709165&sr=1-1)).

I continue to use Linux, with only brief breaks here and there for
forays into other OSs (OS X, Plan 9, and the very occasional Windows).
I'm active in the Madison Linux community as a steering committee
member for MadLUG and am interested in getting new users to try out
Linux (email me with questions/comments).

# How I Work

## Software

I mostly write text.  I write it using Emacs (though for sysadmin
tasks, a bit of vim), under the [XMonad](http://xmonad.org/) tiling
window manager.  For mail, I use [mutt](http://www.mutt.org/) and work
mail is signed with [S/MIME](http://en.wikipedia.org/wiki/S/MIME).  I
use [irssi](http://irssi.org) for IRC and either
[bitlbee](http://www.bitlbee.org) or Pidgin for jabber/AIM/etc.  For
general-purpose documentation, I write
[markdown](http://daringfireball.net/projects/markdown/) processed
with [pandoc](http://johnmacfarlane.net/pandoc/) or
[troff](http://troff.org/) for when things like man pages are needed.
Source-type text is versioned with [git](http://git-scm.com/).

## Hardware 

I use a
[dvorak](http://en.wikipedia.org/wiki/Dvorak_Simplified_Keyboard) key
layout and usually type on a [Happy
Hacking](http://pfuca-store.stores.yahoo.net/haphackeylit1.html) USB
keyboard.  I've been experimenting with a
[Twiddler](http://www.handykey.com/) chorded keyboard/mouse for mobile
computing and am looking for a nice way to interface this device with
a Nexus S Android phone; probably using audio feedback for
interaction.

For monitors, I strongly prefer things in a 4:3 or 5:4 ratio, this is
doubly true for laptops (although, I broke with this and got a [Lemur
Ultrathin](http://knowledge76.com/index.php/LemU1) laptop from
System76) where getting a decent vertical resolution while keeping the
laptop in the 12-14" range is tough.  Laptops which fit this
definition are quite rare currently.  Now that ipads are widely
produced using a 4:3 screen, perhaps this trend will reverse.

## Quixotic Notions

 * Dates should be written in the YYYY-MM-DD format (big endian, like
   all our other numbers)
 * Keep time (where possible) using 24-hour clocks, preferably
   everyone would use UTC (or even better,
   [TAI](http://en.wikipedia.org/wiki/International_Atomic_Time))
 * Metric paper sizes are superior to US paper sizes in every way, the
   side ratio of sqrt(2)/1 is a brilliant hack
 * [Roundabout](http://safety.fhwa.dot.gov/intersection/roundabouts/)
   intersections should be more widely adopted in the US because they
   save fuel and are safer
 * [Dollar coins](http://www.usmint.gov/mint_programs/golden_dollar_coin/index.cfm?action=sacFAQ#eliminate)
   should replace the paper dollar
 * There are exactly 1 billion bytes (1,000,000,000) in a Gigabyte
   (and likewise using SI units for MB, kB, TB).  1,073,741,824 bytes
   are a *gibibyte*