# sencjw

Here's my website.  Some common things are on the navbar.  I've also
worked to preserve any locations that people would have linked to from
elsewhere.  If I've broken a link of yours that used to point to
sencjw.com somewhere, let me know and I'll put it back, [cool URIs don't
change][0]. 

[0]: http://www.w3.org/Provider/Style/URI

## Recent Blog Posts

$recentposts:post()$

For a complete list of posts, see the [blog](blog.html) page.

